### ISSUE TITLE
Requirement: use cleaner syntax of classes

### ISSUE THREAD

**Issue by BK239** [DD2480-G9/metrics-graphics#11]
Use the new syntax for class definitions and constructors (keywords class and constructor). For instance, the code below
```javascript
var Shape = function (id, x, y) {
    this.id = id;
    this.move(x, y);
};
Shape.prototype.move = function (x, y) {
    this.x = x;
    this.y = y;
};
```
should be replaced by the following:
```javascript
class Shape {
    constructor (id, x, y) {
        this.id = id this.move(x, y)
    }
    move (x, y) {
        this.x = x
        this.y = y
    }
}
```
This syntax is clearer, making it easier to understand and search for.

**Comment by lobax** [comment]
I think the description should describe its usage and why we want to use it.

**Comment by RickardBjorklund** [comment]
No longer needed since assignment 3 is done!
