### ISSUE TITLE
Requirement: use built-in method for finding array elements

### ISSUE THREAD

**Issue by BK239** [DD2480-G9/metrics-graphics#12]
Instead of using the traditional filter method with a closure, use the new methods find and findIndex for searching an element in an array! The code below
```javascript
[ 1, 3, 4, 2 ].filter(function (x) { return x > 3; })[0]; // returns 4
```
should be replaced by the following:
```javascript
[ 1, 3, 4, 2 ].find(x => x > 3); // returns 4
```
Make sure these methods are used, keep in mind however that they are not always applicable since find only returns one element as opposed to a list.

**Comment by RickardBjorklund** [comment]
No longer needed since assignment 3 is done!
