### ISSUE TITLE
Requirement: if name of key and variable are equal, use shorthand

### ISSUE THREAD

**Issue by akevert** [DD2480-G9/metrics-graphics#13]
Instead of, as in ES5, doing this:
var a = 1
var b = 2
var c = 3
var d = 4
var obj1 = { a: a, b: b, c: c, d: d }

do this:
var a = 1
var b = 2
var c = 3
var d = 4
var obj1 = { a, b, c, d }
if the names of the keys and the names of the variables are equal.

**Comment by RickardBjorklund** [comment]
No longer needed since assignment 3 is done!
