### ISSUE TITLE
Requirement: Make variables const when applicable

### ISSUE THREAD

**Issue by BK239** [DD2480-G9/metrics-graphics#5]
Replace var with const when applicable, ie when a variable should never assigned to again. For instance ```var PI = 3.14 ``` should be ```const PI = 3.14 ```. Using this keyword will increase correctness and clue the future code reader the intention of the variable. Keep in mind that ```const``` objects are still mutable and can have their methods be called!

**Comment by RickardBjorklund** [comment]
No longer needed since assignment 3 is done!
