### ISSUE TITLE
Requirement: Use template substitutions in strings

### ISSUE THREAD

**Issue by lobax** [DD2480-G9/metrics-graphics#8]
Template substitutions offer a nice syntactic sugar in order to avoid concating strings. Example:

``` javascript
function authorize(user, action) {
  if (!user.hasPrivilege(action)) {
    throw new Error(
      `User ${user.name} is not authorized to do ${action}.`);
  }
}
```

They also add support for multiline strings that will look the way they are formated (eliminating the need to use special characters like `\n`, `\t` etc), making the code more readable. 

See [this](https://hacks.mozilla.org/2015/05/es6-in-depth-template-strings-2/) for more information.

**Comment by RickardBjorklund** [comment]
No longer needed since assignment 3 is done!
