### ISSUE TITLE
Requirement: use default parameter values

### ISSUE THREAD

**Issue by BK239** [DD2480-G9/metrics-graphics#9]
Use default parameters, instead of checking if they're undefined. For example:
Instead of:
```javascript
function (x) {
       if (x === undefined)
              return 7;
       return x;
}
```
do this:
```javascript
function (x=7) {
        return x;
}
```
See http://es6-features.org/#DefaultParameterValues for an explanation. Keep in mind this is one of the more difficult ones since it requires more knowledge about a function's use cases.

**Comment by RickardBjorklund** [comment]
No longer needed since assignment 3 is done!
